import { PAID, FREE, type Lang } from '../api/_lib/config'

// 利用規約・プライバシー・特定商取引法に基づく表記
// ※ 特商法表記は CSV Bridge と内容を揃えてください(下記は「請求時開示」方式の例)

export function LegalContent({ lang, kind }: { lang: Lang; kind: 'terms' | 'tokushoho' }) {
  if (kind === 'tokushoho') {
    const rows: [string, string][] = [
      ['販売事業者', 'Imagination apps(運営責任者の氏名は、請求があった場合に遅滞なく開示します)'],
      ['所在地・電話番号', '請求があった場合に遅滞なく開示します'],
      ['お問い合わせ', 'X(旧Twitter)アカウント @rowyaaisaas へのDMにて'],
      ['販売価格', `${PAID.priceLabel}(フル変換${PAID.creditsPerPack}回分パック)。表示価格以外の費用は発生しません`],
      ['支払方法', 'クレジットカード等(Stripeによる決済)'],
      ['支払時期', '購入手続き完了時'],
      ['提供時期', '決済完了後すぐに利用可能(ライセンスキーをメールでお送りします)'],
      ['有効期限', `購入日から${PAID.packValidityMonths}か月(延長不可)。期限を過ぎた未使用分は利用できません`],
      ['返品・キャンセル', 'デジタル商品の性質上、購入後の返金は原則お受けできません。ただし、サービスの不具合により利用できない場合は個別に対応します'],
      ['動作環境', '最新版のChrome / Safari / Edge / Firefox'],
    ]
    return (
      <div>
        <h2 className="font-serif text-xl font-bold mb-4">特定商取引法に基づく表記</h2>
        <dl className="text-sm divide-y divide-line">
          {rows.map(([k, v]) => (
            <div key={k} className="py-2 grid sm:grid-cols-[9rem_1fr] gap-1">
              <dt className="font-bold text-ink-soft">{k}</dt>
              <dd>{v}</dd>
            </div>
          ))}
        </dl>
      </div>
    )
  }

  if (lang === 'ja') {
    return (
      <div className="space-y-4 text-sm leading-relaxed">
        <h2 className="font-serif text-xl font-bold">利用規約</h2>
        <p>ClearTerms(以下「本ツール」)は、Imagination appsが提供する、契約書・規約などの文章を平易な言葉に言い換える参考ツールです。</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>本ツールは<b>法的アドバイスを提供するものではありません</b>。条項の有利・不利の判断、修正の提案、契約締結の可否の判断は行いません。</li>
          <li>出力はAIによる自動生成であり、誤りや抜けが含まれる可能性があります。内容の正確性・完全性は保証しません。重要な契約は、弁護士等の専門家にご相談ください。</li>
          <li>本ツールの利用により生じた損害について、運営者は責任を負いません(運営者の故意または重過失による場合を除きます)。</li>
          <li>無料版は1日{FREE.dailyLimit}回まで、冒頭部分のみの説明です。不正な手段による制限の回避は禁止します。</li>
          <li>有料パックの有効期限は購入日から{PAID.packValidityMonths}か月です。期限の延長は行いません。</li>
          <li>第三者の秘密情報を入力する場合は、ご自身の責任で、必要な権限や同意の範囲内でご利用ください。</li>
        </ul>
        <h2 className="font-serif text-xl font-bold pt-2">プライバシーポリシー</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li><b>入力した本文</b>:結果の作成のためだけにAnthropic API(Claude)へ送信します。本ツールのサーバー・データベース・ログには保存しません。AnthropicはAPI経由のデータをモデルの学習に使用しません。</li>
          <li><b>PDF</b>:お使いのブラウザ内で文字を読み取ります。ファイル自体は送信しません。</li>
          <li><b>メールアドレス</b>:無料版の本人確認・利用回数の管理、購入時のライセンスキー送付、期限前のお知らせに使用します。</li>
          <li><b>IPアドレス</b>:不正利用防止のため、復元できない形(ハッシュ値)に変換して利用回数の管理にのみ使用します。</li>
          <li><b>決済情報</b>:Stripeが処理し、本ツールはカード情報を保持しません。</li>
          <li>利用する外部サービス:Anthropic(AI処理)、Supabase(データベース)、Resend(メール送信)、Stripe(決済)、Vercel(ホスティング)。</li>
        </ul>
      </div>
    )
  }

  return (
    <div className="space-y-4 text-sm leading-relaxed">
      <h2 className="font-serif text-xl font-bold">Terms of Use</h2>
      <p>ClearTerms ("the Tool") is provided by Imagination apps as a reference tool that rewrites contracts and terms into plain language.</p>
      <ul className="list-disc pl-5 space-y-1">
        <li>The Tool <b>does not provide legal advice</b>. It does not judge whether terms are favorable, suggest changes, or advise whether to sign.</li>
        <li>Output is generated by AI and may contain errors or omissions. We do not guarantee accuracy or completeness. For important contracts, consult a lawyer or other qualified professional.</li>
        <li>We are not liable for any damages arising from use of the Tool, except in cases of our intentional misconduct or gross negligence.</li>
        <li>The free version explains only the beginning of a document, up to {FREE.dailyLimit} times a day. Circumventing these limits is prohibited.</li>
        <li>Paid packs are valid for {PAID.packValidityMonths} months from purchase and are not extendable.</li>
        <li>If you enter someone else's confidential information, you are responsible for having the necessary rights or consent.</li>
      </ul>
      <h2 className="font-serif text-xl font-bold pt-2">Privacy Policy</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li><b>Your text</b> is sent to the Anthropic API (Claude) only to produce the result. We do not store it on our servers, database, or logs. Anthropic does not train models on API data.</li>
        <li><b>PDFs</b> are read inside your browser; the file itself is never uploaded.</li>
        <li><b>Email address</b>: used to verify free usage, send your license key, and remind you before credits expire.</li>
        <li><b>IP address</b>: converted to a one-way hash and used only to limit abuse of the free version.</li>
        <li><b>Payments</b> are processed by Stripe; we never see your card details.</li>
        <li>Services we use: Anthropic (AI), Supabase (database), Resend (email), Stripe (payments), Vercel (hosting).</li>
      </ul>
    </div>
  )
}
